apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-server-pvc
spec:
  accessModes:
    - ReadWriteOnce # Você pode gravar e ler o volume some no mesmo node
  resources:
    requests:
      storage: 5Gi